### ISSUE TITLE
Secondary menu already occupied

### ISSUE THREAD

**Issue by murrayac** [billerickson/Genesis-Subpages-as-Secondary-Menu#7]
Using this plugin with Genesis No Sidebar Pro and the secondary menu is already being used. Do you have a workaround for this?

**Comment by billerickson** [comment]
This plugin only works with the secondary menu. I haven't used the No Sidebar Pro theme before so am not sure what it does with the secondary nav, but I recommend you modify that theme to use a different menu (ex: create a 'tertiary' menu location). 

Or you can modify this plugin to use an alternate menu location, but be sure to also increase the version number to something like 99 so that it doesn't receive any future updates which will overwrite your changes.
