### ISSUE TITLE
Superfish/dropdowns not working

### ISSUE THREAD

**Issue by anniesmidt** [billerickson/Genesis-Subpages-as-Secondary-Menu#9]
Hi Bill —

Firstly, thanks so much for making and distributing this plugin. Once I get it working properly, it's going to streamline the site I'm building in such a pleasing way.

Issue: I'm using Genesis with the default "sample" child theme. The plug-in is working from a logic standpoint — it pulls the right secondary menu in and puts it where it goes. However, it's printing out all of the second, third and fourth level items, rather than presenting them in a dropdowns.

It's picking up Sample's styling for font/color but not for (I guess) superfish. The main menu on the page (not being affected by your plugin) does it's superfish pulldown stuff just fine. 

I only started playing with Genesis about 24 hours ago for the first time, so I'm not that familiar with it. But perhaps something has changed with Genesis's classes since this plugin was last updated? Just a guess. 

Any help would be super-appreciated... I've tried troubleshooting with every idea I can come up with... and I'm excited to use this plugin!

Screenshot shows secondary menu showing up but printing out all it's subpages as if they're top-level.
![screen shot 2016-11-08 at 3 52 55 pm](https://cloud.githubusercontent.com/assets/2166217/20116766/9b6b9af0-a5cb-11e6-8453-1688ac9f24a0.png)

Thank you
Annie

**Comment by billerickson** [comment]
Unfortunately this is something you'll need to resolve by updating your theme's CSS. 

Your theme's menu styling assumes certain classes that are added by the WordPress menu function (`wp_nav_menu()`). But this plugin doesn't use `wp_nav_menu()` - it uses `wp_list_pages()` since we're dynamically listing a set of pages (rather than a manually managed menu). This means the classes on the menu items will differ from those of a standard menu.

For instance, a standard WordPress menu will put the submenu items inside `<ul class="sub-menu">`, but the submenus produced by this plugin don't have that class.

The solution is to update your theme's CSS to also apply its styling to the output of this plugin.
